harleen-acog:
  name: harleen-acog
  avatar: https://avatars.githubusercontent.com/u/274802161?v=4
  bio:: undefined
  github: https://github.com/harleen-acog
  followers: 0
  repos: 2

  linkedin: https://linkedin.com/in/harleen-acog
  email: harleen-acog@email.com
  phone: "+91-9876543210"

rajat-acog:
  name: rajat-acog
  avatar: https://avatars.githubusercontent.com/u/274802982?v=4
  bio:: undefined
  github: https://github.com/rajat-acog
  followers: 0
  repos: 1
  
  linkedin: https://linkedin.com/in/rajat-acog
  email: rajat-acog@email.com
  phone: "+91-9876543210"

swati-acog:
  name: swati-acog
  avatar: https://avatars.githubusercontent.com/u/274803465?v=4
  bio:: undefined
  github: https://github.com/swati-acog
  followers: 0
  repos: 2

  linkedin: https://linkedin.com/in/swati-acog
  email: swati-acog@email.com
  phone: "+91-9876543210"
