name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login dockerhub.aganitha.ai:4443 -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build -t astro-app ./portfolio

      - name: Tag Image
        run: docker tag astro-app dockerhub.aganitha.ai:4443/chem/rajat-assignment:latest

      - name: Push Image
        run: docker push dockerhub.aganitha.ai:4443/rajat-assignment:latest

      - name: Deploy to own3
        uses: appleboy/ssh-action@v1
        with:
          host: own3.aganitha.ai
          username: brajat
          port: 2322
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull dockerhub.aganitha.ai:4443/rajat-assignment:latest
            docker stop rajat-assignment || true
            docker rm rajat-assignment || true
            docker run -d -p 80:80 --name rajat-assignment dockerhub.aganitha.ai:4443/rajat-assignment:latest
