name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login dockerhub.aganitha.ai:4443 -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Image
        run: docker build --no-cache -t astro-app ./portfolio

      - name: Tag Image
        run: docker tag astro-app dockerhub.aganitha.ai:4443/rajat-assignment/astro-blog:latest

      - name: Push Image
        run: docker push dockerhub.aganitha.ai:4443/rajat-assignment/astro-blog:latest

      - name: Deploy to own3
        uses: appleboy/ssh-action@v1
        with:
          host: own3.aganitha.ai
          username: brajat
          port: 2322
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~

            # pull latest image
            docker pull dockerhub.aganitha.ai:4443/rajat-assignment/astro-blog:latest

            # stop existing container (if running via compose)
            docker compose down || true

            # start again with latest image
            docker compose up -d
